# Generated by Django 3.2.6 on 2021-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qid', models.IntegerField(verbose_name='Question ID')),
                ('choice', models.IntegerField(verbose_name='Options')),
                ('answertext', models.CharField(max_length=200, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('account', models.CharField(max_length=200, unique=True, verbose_name='Account')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('gendar', models.IntegerField(default=1, verbose_name='Sex')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
        ),
    ]
