# Generated by Django 3.2.6 on 2021-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findbestjob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='工作名称')),
                ('company', models.CharField(max_length=200, verbose_name='企业名称')),
                ('ind1', models.IntegerField(default=1, verbose_name='指标1')),
                ('ind2', models.IntegerField(default=1, verbose_name='指标2')),
                ('ind3', models.IntegerField(default=1, verbose_name='指标3')),
                ('ind4', models.IntegerField(default=1, verbose_name='指标4')),
                ('ind5', models.IntegerField(default=1, verbose_name='指标5')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gendar',
            new_name='gender',
        ),
    ]
