# Generated by Django 3.2.6 on 2021-08-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findbestjob', '0002_auto_20210822_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=15, verbose_name='Age'),
        ),
    ]
