# Generated by Django 3.2.6 on 2021-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findbestjob', '0003_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answertext',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='qid',
        ),
        migrations.AddField(
            model_name='answer',
            name='q1',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 1'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q10',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 10'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q11',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 11'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q12',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 12'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q13',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 13'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q14',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 14'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q15',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 15'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q16',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 16'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q17',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 17'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q18',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 18'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q19',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 19'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q2',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 2'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q20',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 20'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q21',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 21'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q22',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 22'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q23',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 23'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q3',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 3'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q4',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 4'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q5',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 5'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q6',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 6'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q7',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 7'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q8',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 8'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q9',
            field=models.CharField(max_length=10, null=True, verbose_name='Question 9'),
        ),
        migrations.AddField(
            model_name='answer',
            name='sid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ind6',
            field=models.IntegerField(default=1, verbose_name='指标6'),
        ),
    ]
